export const routes = [
  "/",
  "/blog",
  "/blog/aiims-salary-perks",
  "/blog/cho-career-path",
  "/blog/dsssb-exam-pattern",
  "/blog/esic-recruitment",
  "/blog/mock-test-benefits",
  "/blog/norcet-2026-preparation-strategy",
  "/blog/rrb-nursing-officer-strategy",
  "/blog/time-management-nurses",
  "/blog/top-books-nursing",
  "/courses",
  "/events",
  "/free-demo-content",
  "/freetest",
  "/join-batch",
  "/mock-tests",
  "/offers-alters",
  "/podcast",
  "/selected-nursing-officers",
  "/subject-tests",
  "/vacancy-results"
] as const;
